name: CI
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ENTRYPOINT: https://localhost
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vercel Deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: 00JYhXTaOzqgMLQ8eQD9NaGU # Required
          github-token: ${{ secrets.CRED_TOKEN }} #Optional 
          vercel-org-id: CCmTh620AqxmTtmWAcRnR5O5  #Required
          vercel-project-id: prj_amtzY1Lda702dSw9hYJrgzMWuZY9 #Required 
          working-directory: ./pwa
